version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    # Persist the data (so it doesn't have to build each time)
    # volumes:
    #  - ./postgres-data:/var/lib/postgresql/data
    #  - ./data:/tmp
  
  adminer:
    image: adminer
    restart: always
    ports:
      - ${PUBLIC_ADMINER_PORT}:8080

  web:
    build: .
    ports:
      - ${PUBLIC_WEB_PORT}:5000
    # For development, only
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app